spring:
  datasource:
    url: jdbc:sqlite:./resources/library.sqlite
    driver-class-name: org.sqlite.JDBC

mybatis:
  mapper-locations: classpath:dataImpl/*/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true